#
# Workaround for Ansible v2.8:
# gather facts for individual execution of roles
# see issue: https://github.com/ansible/ansible/issues/57529
- hosts: all

# Setup base configuration
- hosts: all
  any_errors_fatal: True
  roles:
    - name: network
      tags: network
    - name: host_config
      tags: host_config, network
    - name: time
      tags: time
    - name: zsh
      tags: zsh
    - name: user_config
      tags: user_config
    - name: ssh_config
      tags: ssh_config
    - name: locale_config
      tags: locale_config
    - name: vis_base
      tags: vis_base
  tags: config, base

# Setup base user environment
- hosts: all
  any_errors_fatal: True
  roles:
    - name: motd
      tags: motd
    - name: vim
      tags: vim
  tags: env, base

- hosts: all
  any_errors_fatal: True
  roles:
    - name: pi-hardening
      tags: pi-hardening, base
    - name: pi-mac-address
      tags: pi-mac-address, base

- hosts: asvz_bots
  any_errors_fatal: True
  roles:
    - role: asvz_bot
      tags: asvz_bot
