---

- name: Install default stuff (Debian-specific)
  become: True
  package:
    name: "{{ item }}"
    state: present
    cache_valid_time: 86400
    update_cache: yes
  with_items: "{{ vis_base_debian_specific_pkgs }}"
  when: ansible_distribution != "Fedora"

- name: Install default stuff (Fedora-specific)
  become: True
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vis_base_fedora_specific_pkgs }}"
  when: ansible_distribution == "Fedora"

- name: Install default stuff
  become: True
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vis_base_pkgs }}"

- name: Enable persistent logging
  become: True
  replace:
    path: /etc/systemd/journald.conf
    regexp: ^#Storage=auto$
    replace: Storage=persistent
  notify: restart systemd-journald

- name: Set a maximum size for journald logs
  become: True
  replace:
    path: /etc/systemd/journald.conf
    regexp: ^#?SystemMaxUse=.*$
    replace: "SystemMaxUse={{ vis_base_journald_max_size }}"
  notify: restart systemd-journald

- name: Add the VIS aptly repository key
  become: True
  apt_key:
    data: "{{ vis_base_aptly_repository_key }}"
    state: present
  when: ansible_distribution != "Fedora"

- name: Add the VIS monitoring repository
  become: True
  apt_repository:
    repo: 'deb http://apt.vis.ethz.ch/aptly/vis-buster buster main'
    update_cache: yes
    state: present
  when: ansible_distribution != "Fedora"
  register: aptly_repo

- name: Update apt cache
  become: True
  apt:
    update_cache: True
  when: aptly_repo.changed
