---

- name: Ensure /etc/motd is present
  become: True
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Remove the uname motd
  become: True
  file:
    path: /etc/update-motd.d/10-uname
    state: absent
  when: ansible_distribution != "Fedora"

- name: Copy the dynamic motd contents
  become: True
  template:
    src: "{{ item }}"
    dest: "/etc/update-motd.d/{{ item | basename | splitext | first }}"
    owner: root
    group: root
    mode: 0755
  with_fileglob: ../templates/update-motd.d/*.j2
  when: ansible_distribution != "Fedora"
