---
- name: Set hostname to ansible hostname
  become: True
  hostname:
    name: "{{ inventory_hostname }}"

- name: Build /etc/hosts for every server
  become: True
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution != "Fedora" and host_config_update_etc_hosts
