---

- name: Ensure that vim is installed
  become: True
  package:
    name: "{%- if ansible_distribution == 'Debian' -%} vim-nox {%- elif ansible_distribution == 'Fedora' -%} vim {%- endif -%}"
    state: present

# NOTE: user_config_users is defined by the role 'user_config'
- name: Upload default vimrc
  become: True
  template:
    src: vimrc.j2
    dest: "/home/{{ item }}/.vimrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0664
  with_items: "{{ user_config_users }}"

- name: Upload default vimrc to root
  become: True
  template:
    src: vimrc.j2
    dest: "/root/.vimrc"
    owner: "root"
    group: "root"
    mode: 0664
