---
- name: Ensure .ssh folder exists for ssh default users
  become: True
  file:
    path: "/home/{{ item }}/.ssh/"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
  with_items:
    - "{{ ssh_config_default_users }}"

# Taken from the old security role and modified for the new key format
# Build privileged authorized_keys
- name: Create empty key string
  set_fact:
    ssh_config_authorized_key: ""

- name: Create concatenated key files for privileged user
  set_fact:
    ssh_config_authorized_key: "{{ [ssh_config_authorized_key, lookup('file', 'sshkeys/{{ item }}')] | join('\n') }}"
  with_items: "{{ ssh_config_privileged_users }}"

- name: Set up authorized keys for privileged user
  become: True
  authorized_key:
    user: "{{ ssh_config_privileged_user }}"
    state: present
    key: "{{ ssh_config_authorized_key }}"
    exclusive: yes

- name: Create empty key string
  set_fact:
    ssh_config_authorized_key: ""

- name: Create concatenated key files for unprivileged user
  set_fact:
    ssh_config_authorized_key: "{{ [ssh_config_authorized_key, lookup('file', 'sshkeys/{{ item }}')] | join('\n') }}"
  with_items: "{{ ssh_config_privileged_users + (ssh_config_unprivileged_users | default([]))}}"

- name: Set up authorized keys for unprivileged user
  become: True
  authorized_key:
    user: "{{ ssh_config_unprivileged_user }}"
    state: present
    key: "{{ ssh_config_authorized_key }}"
    exclusive: yes

- name: Create ssh-user group
  become: True
  group:
    name: ssh-user
    state: present

- name: Add necessary users to ssh-user group
  become: True
  user:
    name: "{{ item }}"
    groups: ssh-user
    append: yes
  with_items: "{{ ssh_config_default_users + ssh_config_additional_users }}"
  notify: restart sshd

- name: Upload hardened ssh configs
  become: True
  template:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - ssh_config
    - sshd_config
  notify: restart sshd

- name: Upload moduli for DH key exchange
  become: True
  copy:
    src: moduli
    dest: /etc/ssh/moduli
    owner: root
    group: root
    mode: 0644
  notify: restart sshd
